name: Repository Events
on:
  push:
    branches:
      - main
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3

      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change Working Dir
        working-directory: /home/runner
        run: pwd      

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api https://api.github.com/repos/octocat/Spoon-Knife/issues        

      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message with params
        run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Setting a debug message with params
        run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Setting an warning message with params
        run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Setting an notice message with params
        run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
      - name: Group of logs
        run: |
          echo "::group::My group title"
          echo "Inside group"
          echo "::endgroup::"
      - name: Masking a value
        run: echo "::add-mask::Secret String"
      - name: Echo a secret
        run: echo "Secret String"          

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with:
          who-to-greet: Ali
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"        
        